apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80 to the cluster
      targetPort: 80  # Target port in the container
  type: NodePort  # Exposes the service on a NodePort
